//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatCatalogs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatCatalogs()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int IdCatalog { get; set; }
        public Nullable<int> IdProvider { get; set; }
        public string Season { get; set; }
        public Nullable<System.DateTime> StarActiveDate { get; set; }
        public Nullable<System.DateTime> EndActiveDate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public bool IsEnabled { get; set; }
    
        public virtual CatProviders CatProviders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
    }
}
