//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagesProduct
    {
        public int IdImage { get; set; }
        public int IdProduct { get; set; }
        public string Decription { get; set; }
        public byte[] Image { get; set; }
        public System.DateTime DateUpdate { get; set; }
        public bool IsEnabled { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
